/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v19/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v19.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v19.model.AudienceListServiceLogicalCondition;
import jp.co.yahoo.adssearchapi.v19.model.AudienceListServiceLogicalRuleOperand;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AudienceListServiceLogicalGroupは、組合せグループの情報を保持するオブジェクトです。&lt;br&gt; このフィールドは、ADDおよびSET時に必須となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AudienceListServiceLogicalGroup is an object that holds combination group information.&lt;br&gt; This field is required in ADD and SET operation.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  AudienceListServiceLogicalGroup.JSON_PROPERTY_LOGICAL_CONDITION,
  AudienceListServiceLogicalGroup.JSON_PROPERTY_LOGICAL_OPERAND
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AudienceListServiceLogicalGroup {
  public static final String JSON_PROPERTY_LOGICAL_CONDITION = "logicalCondition";
  private AudienceListServiceLogicalCondition logicalCondition;

  public static final String JSON_PROPERTY_LOGICAL_OPERAND = "logicalOperand";
  private List<AudienceListServiceLogicalRuleOperand> logicalOperand;

  public AudienceListServiceLogicalGroup() {
  }

  public AudienceListServiceLogicalGroup logicalCondition(AudienceListServiceLogicalCondition logicalCondition) {
    
    this.logicalCondition = logicalCondition;
    return this;
  }

   /**
   * Get logicalCondition
   * @return logicalCondition
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGICAL_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AudienceListServiceLogicalCondition getLogicalCondition() {
    return logicalCondition;
  }


  @JsonProperty(JSON_PROPERTY_LOGICAL_CONDITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogicalCondition(AudienceListServiceLogicalCondition logicalCondition) {
    this.logicalCondition = logicalCondition;
  }


  public AudienceListServiceLogicalGroup logicalOperand(List<AudienceListServiceLogicalRuleOperand> logicalOperand) {
    
    this.logicalOperand = logicalOperand;
    return this;
  }

  public AudienceListServiceLogicalGroup addLogicalOperandItem(AudienceListServiceLogicalRuleOperand logicalOperandItem) {
    if (this.logicalOperand == null) {
      this.logicalOperand = new ArrayList<>();
    }
    this.logicalOperand.add(logicalOperandItem);
    return this;
  }

   /**
   * Get logicalOperand
   * @return logicalOperand
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGICAL_OPERAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AudienceListServiceLogicalRuleOperand> getLogicalOperand() {
    return logicalOperand;
  }


  @JsonProperty(JSON_PROPERTY_LOGICAL_OPERAND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogicalOperand(List<AudienceListServiceLogicalRuleOperand> logicalOperand) {
    this.logicalOperand = logicalOperand;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AudienceListServiceLogicalGroup audienceListServiceLogicalGroup = (AudienceListServiceLogicalGroup) o;
    return Objects.equals(this.logicalCondition, audienceListServiceLogicalGroup.logicalCondition) &&
        Objects.equals(this.logicalOperand, audienceListServiceLogicalGroup.logicalOperand);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logicalCondition, logicalOperand);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AudienceListServiceLogicalGroup {\n");
    sb.append("    logicalCondition: ").append(toIndentedString(logicalCondition)).append("\n");
    sb.append("    logicalOperand: ").append(toIndentedString(logicalOperand)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

