/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v17/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v17.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportCompressType;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportDateRange;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportDateRangeType;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportDecimalPartDisplayType;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportDownloadEncode;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportDownloadFormat;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportFilter;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportJobStatus;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportLanguage;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportSkipColumnHeader;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportSkipReportSummary;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportSortField;
import jp.co.yahoo.adssearchapi.v17.model.SsaReportDefinitionServiceReportType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;SsaReportDefinitionオブジェクトは、レポートの情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;SsaReportDefinition object describes report information.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  SsaReportDefinition.JSON_PROPERTY_ACCOUNT_ID,
  SsaReportDefinition.JSON_PROPERTY_COMPLETE_TIME,
  SsaReportDefinition.JSON_PROPERTY_DATE_RANGE,
  SsaReportDefinition.JSON_PROPERTY_FIELDS,
  SsaReportDefinition.JSON_PROPERTY_FILTERS,
  SsaReportDefinition.JSON_PROPERTY_REPORT_COMPRESS_TYPE,
  SsaReportDefinition.JSON_PROPERTY_REPORT_DATE_RANGE_TYPE,
  SsaReportDefinition.JSON_PROPERTY_REPORT_DECIMAL_PART_DISPLAY_TYPE,
  SsaReportDefinition.JSON_PROPERTY_REPORT_DOWNLOAD_ENCODE,
  SsaReportDefinition.JSON_PROPERTY_REPORT_DOWNLOAD_FORMAT,
  SsaReportDefinition.JSON_PROPERTY_REPORT_JOB_ERROR_DETAIL,
  SsaReportDefinition.JSON_PROPERTY_REPORT_JOB_ID,
  SsaReportDefinition.JSON_PROPERTY_REPORT_JOB_STATUS,
  SsaReportDefinition.JSON_PROPERTY_REPORT_LANGUAGE,
  SsaReportDefinition.JSON_PROPERTY_REPORT_NAME,
  SsaReportDefinition.JSON_PROPERTY_REPORT_SKIP_COLUMN_HEADER,
  SsaReportDefinition.JSON_PROPERTY_REPORT_SKIP_REPORT_SUMMARY,
  SsaReportDefinition.JSON_PROPERTY_REPORT_TYPE,
  SsaReportDefinition.JSON_PROPERTY_REQUEST_TIME,
  SsaReportDefinition.JSON_PROPERTY_SORT_FIELDS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SsaReportDefinition {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  private Long accountId;

  public static final String JSON_PROPERTY_COMPLETE_TIME = "completeTime";
  private String completeTime;

  public static final String JSON_PROPERTY_DATE_RANGE = "dateRange";
  private SsaReportDefinitionServiceReportDateRange dateRange;

  public static final String JSON_PROPERTY_FIELDS = "fields";
  private List<String> fields;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  private List<SsaReportDefinitionServiceReportFilter> filters;

  public static final String JSON_PROPERTY_REPORT_COMPRESS_TYPE = "reportCompressType";
  private SsaReportDefinitionServiceReportCompressType reportCompressType;

  public static final String JSON_PROPERTY_REPORT_DATE_RANGE_TYPE = "reportDateRangeType";
  private SsaReportDefinitionServiceReportDateRangeType reportDateRangeType;

  public static final String JSON_PROPERTY_REPORT_DECIMAL_PART_DISPLAY_TYPE = "reportDecimalPartDisplayType";
  private SsaReportDefinitionServiceReportDecimalPartDisplayType reportDecimalPartDisplayType;

  public static final String JSON_PROPERTY_REPORT_DOWNLOAD_ENCODE = "reportDownloadEncode";
  private SsaReportDefinitionServiceReportDownloadEncode reportDownloadEncode;

  public static final String JSON_PROPERTY_REPORT_DOWNLOAD_FORMAT = "reportDownloadFormat";
  private SsaReportDefinitionServiceReportDownloadFormat reportDownloadFormat;

  public static final String JSON_PROPERTY_REPORT_JOB_ERROR_DETAIL = "reportJobErrorDetail";
  private String reportJobErrorDetail;

  public static final String JSON_PROPERTY_REPORT_JOB_ID = "reportJobId";
  private Long reportJobId;

  public static final String JSON_PROPERTY_REPORT_JOB_STATUS = "reportJobStatus";
  private SsaReportDefinitionServiceReportJobStatus reportJobStatus;

  public static final String JSON_PROPERTY_REPORT_LANGUAGE = "reportLanguage";
  private SsaReportDefinitionServiceReportLanguage reportLanguage;

  public static final String JSON_PROPERTY_REPORT_NAME = "reportName";
  private String reportName;

  public static final String JSON_PROPERTY_REPORT_SKIP_COLUMN_HEADER = "reportSkipColumnHeader";
  private SsaReportDefinitionServiceReportSkipColumnHeader reportSkipColumnHeader;

  public static final String JSON_PROPERTY_REPORT_SKIP_REPORT_SUMMARY = "reportSkipReportSummary";
  private SsaReportDefinitionServiceReportSkipReportSummary reportSkipReportSummary;

  public static final String JSON_PROPERTY_REPORT_TYPE = "reportType";
  private SsaReportDefinitionServiceReportType reportType;

  public static final String JSON_PROPERTY_REQUEST_TIME = "requestTime";
  private String requestTime;

  public static final String JSON_PROPERTY_SORT_FIELDS = "sortFields";
  private List<SsaReportDefinitionServiceReportSortField> sortFields;

  public SsaReportDefinition() {
  }

  public SsaReportDefinition accountId(Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウントIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account ID.&lt;/div&gt; 
   * @return accountId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }


  public SsaReportDefinition completeTime(String completeTime) {
    
    this.completeTime = completeTime;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ジョブの完了時刻です。&lt;br&gt; ※YYYY/MM/DD hh:mm:ss形式になります。&lt;br&gt; ※hhは24時間表記になります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Completion time of Report Job request.&lt;br&gt; *Displays in YYYY/MM/DD hh:mm:ss form.&lt;br&gt; *hh will display in 24-hour time.&lt;/div&gt; 
   * @return completeTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPLETE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCompleteTime() {
    return completeTime;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompleteTime(String completeTime) {
    this.completeTime = completeTime;
  }


  public SsaReportDefinition dateRange(SsaReportDefinitionServiceReportDateRange dateRange) {
    
    this.dateRange = dateRange;
    return this;
  }

   /**
   * Get dateRange
   * @return dateRange
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportDateRange getDateRange() {
    return dateRange;
  }


  @JsonProperty(JSON_PROPERTY_DATE_RANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateRange(SsaReportDefinitionServiceReportDateRange dateRange) {
    this.dateRange = dateRange;
  }


  public SsaReportDefinition fields(List<String> fields) {
    
    this.fields = fields;
    return this;
  }

  public SsaReportDefinition addFieldsItem(String fieldsItem) {
    if (this.fields == null) {
      this.fields = new ArrayList<>();
    }
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;フィールド（レポートの出力項目名）です。&lt;br&gt; ADD時、このフィールドは必須となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Item name of the report.&lt;br&gt; Can appoint the value retrieved from getReportFields.&lt;br&gt; This field is required in ADD operation.&lt;/div&gt; 
   * @return fields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getFields() {
    return fields;
  }


  @JsonProperty(JSON_PROPERTY_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFields(List<String> fields) {
    this.fields = fields;
  }


  public SsaReportDefinition filters(List<SsaReportDefinitionServiceReportFilter> filters) {
    
    this.filters = filters;
    return this;
  }

  public SsaReportDefinition addFiltersItem(SsaReportDefinitionServiceReportFilter filtersItem) {
    if (this.filters == null) {
      this.filters = new ArrayList<>();
    }
    this.filters.add(filtersItem);
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SsaReportDefinitionServiceReportFilter> getFilters() {
    return filters;
  }


  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilters(List<SsaReportDefinitionServiceReportFilter> filters) {
    this.filters = filters;
  }


  public SsaReportDefinition reportCompressType(SsaReportDefinitionServiceReportCompressType reportCompressType) {
    
    this.reportCompressType = reportCompressType;
    return this;
  }

   /**
   * Get reportCompressType
   * @return reportCompressType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_COMPRESS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportCompressType getReportCompressType() {
    return reportCompressType;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_COMPRESS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportCompressType(SsaReportDefinitionServiceReportCompressType reportCompressType) {
    this.reportCompressType = reportCompressType;
  }


  public SsaReportDefinition reportDateRangeType(SsaReportDefinitionServiceReportDateRangeType reportDateRangeType) {
    
    this.reportDateRangeType = reportDateRangeType;
    return this;
  }

   /**
   * Get reportDateRangeType
   * @return reportDateRangeType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_DATE_RANGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportDateRangeType getReportDateRangeType() {
    return reportDateRangeType;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DATE_RANGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportDateRangeType(SsaReportDefinitionServiceReportDateRangeType reportDateRangeType) {
    this.reportDateRangeType = reportDateRangeType;
  }


  public SsaReportDefinition reportDecimalPartDisplayType(SsaReportDefinitionServiceReportDecimalPartDisplayType reportDecimalPartDisplayType) {
    
    this.reportDecimalPartDisplayType = reportDecimalPartDisplayType;
    return this;
  }

   /**
   * Get reportDecimalPartDisplayType
   * @return reportDecimalPartDisplayType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_DECIMAL_PART_DISPLAY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportDecimalPartDisplayType getReportDecimalPartDisplayType() {
    return reportDecimalPartDisplayType;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DECIMAL_PART_DISPLAY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportDecimalPartDisplayType(SsaReportDefinitionServiceReportDecimalPartDisplayType reportDecimalPartDisplayType) {
    this.reportDecimalPartDisplayType = reportDecimalPartDisplayType;
  }


  public SsaReportDefinition reportDownloadEncode(SsaReportDefinitionServiceReportDownloadEncode reportDownloadEncode) {
    
    this.reportDownloadEncode = reportDownloadEncode;
    return this;
  }

   /**
   * Get reportDownloadEncode
   * @return reportDownloadEncode
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_DOWNLOAD_ENCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportDownloadEncode getReportDownloadEncode() {
    return reportDownloadEncode;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DOWNLOAD_ENCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportDownloadEncode(SsaReportDefinitionServiceReportDownloadEncode reportDownloadEncode) {
    this.reportDownloadEncode = reportDownloadEncode;
  }


  public SsaReportDefinition reportDownloadFormat(SsaReportDefinitionServiceReportDownloadFormat reportDownloadFormat) {
    
    this.reportDownloadFormat = reportDownloadFormat;
    return this;
  }

   /**
   * Get reportDownloadFormat
   * @return reportDownloadFormat
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_DOWNLOAD_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportDownloadFormat getReportDownloadFormat() {
    return reportDownloadFormat;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DOWNLOAD_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportDownloadFormat(SsaReportDefinitionServiceReportDownloadFormat reportDownloadFormat) {
    this.reportDownloadFormat = reportDownloadFormat;
  }


  public SsaReportDefinition reportJobErrorDetail(String reportJobErrorDetail) {
    
    this.reportJobErrorDetail = reportJobErrorDetail;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;レポートジョブのエラー詳細です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Error details of Report Job.&lt;/div&gt; 
   * @return reportJobErrorDetail
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_JOB_ERROR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportJobErrorDetail() {
    return reportJobErrorDetail;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_JOB_ERROR_DETAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportJobErrorDetail(String reportJobErrorDetail) {
    this.reportJobErrorDetail = reportJobErrorDetail;
  }


  public SsaReportDefinition reportJobId(Long reportJobId) {
    
    this.reportJobId = reportJobId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;レポートジョブIDです。&lt;br&gt; REMOVE時、このフィールドは必須となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Report Job ID.&lt;br&gt; This field is required in REMOVE operation.&lt;/div&gt; 
   * @return reportJobId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getReportJobId() {
    return reportJobId;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportJobId(Long reportJobId) {
    this.reportJobId = reportJobId;
  }


  public SsaReportDefinition reportJobStatus(SsaReportDefinitionServiceReportJobStatus reportJobStatus) {
    
    this.reportJobStatus = reportJobStatus;
    return this;
  }

   /**
   * Get reportJobStatus
   * @return reportJobStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_JOB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportJobStatus getReportJobStatus() {
    return reportJobStatus;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_JOB_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportJobStatus(SsaReportDefinitionServiceReportJobStatus reportJobStatus) {
    this.reportJobStatus = reportJobStatus;
  }


  public SsaReportDefinition reportLanguage(SsaReportDefinitionServiceReportLanguage reportLanguage) {
    
    this.reportLanguage = reportLanguage;
    return this;
  }

   /**
   * Get reportLanguage
   * @return reportLanguage
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportLanguage getReportLanguage() {
    return reportLanguage;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportLanguage(SsaReportDefinitionServiceReportLanguage reportLanguage) {
    this.reportLanguage = reportLanguage;
  }


  public SsaReportDefinition reportName(String reportName) {
    
    this.reportName = reportName;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;レポート名称です。&lt;br&gt; ADD時、このフィールドは必須となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Name of the report.&lt;br&gt; This field is required in ADD operation.&lt;/div&gt; 
   * @return reportName
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportName() {
    return reportName;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportName(String reportName) {
    this.reportName = reportName;
  }


  public SsaReportDefinition reportSkipColumnHeader(SsaReportDefinitionServiceReportSkipColumnHeader reportSkipColumnHeader) {
    
    this.reportSkipColumnHeader = reportSkipColumnHeader;
    return this;
  }

   /**
   * Get reportSkipColumnHeader
   * @return reportSkipColumnHeader
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_SKIP_COLUMN_HEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportSkipColumnHeader getReportSkipColumnHeader() {
    return reportSkipColumnHeader;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_SKIP_COLUMN_HEADER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportSkipColumnHeader(SsaReportDefinitionServiceReportSkipColumnHeader reportSkipColumnHeader) {
    this.reportSkipColumnHeader = reportSkipColumnHeader;
  }


  public SsaReportDefinition reportSkipReportSummary(SsaReportDefinitionServiceReportSkipReportSummary reportSkipReportSummary) {
    
    this.reportSkipReportSummary = reportSkipReportSummary;
    return this;
  }

   /**
   * Get reportSkipReportSummary
   * @return reportSkipReportSummary
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_SKIP_REPORT_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportSkipReportSummary getReportSkipReportSummary() {
    return reportSkipReportSummary;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_SKIP_REPORT_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportSkipReportSummary(SsaReportDefinitionServiceReportSkipReportSummary reportSkipReportSummary) {
    this.reportSkipReportSummary = reportSkipReportSummary;
  }


  public SsaReportDefinition reportType(SsaReportDefinitionServiceReportType reportType) {
    
    this.reportType = reportType;
    return this;
  }

   /**
   * Get reportType
   * @return reportType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SsaReportDefinitionServiceReportType getReportType() {
    return reportType;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportType(SsaReportDefinitionServiceReportType reportType) {
    this.reportType = reportType;
  }


  public SsaReportDefinition requestTime(String requestTime) {
    
    this.requestTime = requestTime;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;リクエストの到着日時です。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。&lt;br&gt; ※フォーマット: yyyy/MM/dd HH:mm:ss&lt;br&gt; ※HHは24時間表記になります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Arrival date and time of your request.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input.&lt;br&gt; *Format: yyyy/MM/dd HH:mm:ss *HH will display in 24-hour time.&lt;/div&gt; 
   * @return requestTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REQUEST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRequestTime() {
    return requestTime;
  }


  @JsonProperty(JSON_PROPERTY_REQUEST_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRequestTime(String requestTime) {
    this.requestTime = requestTime;
  }


  public SsaReportDefinition sortFields(List<SsaReportDefinitionServiceReportSortField> sortFields) {
    
    this.sortFields = sortFields;
    return this;
  }

  public SsaReportDefinition addSortFieldsItem(SsaReportDefinitionServiceReportSortField sortFieldsItem) {
    if (this.sortFields == null) {
      this.sortFields = new ArrayList<>();
    }
    this.sortFields.add(sortFieldsItem);
    return this;
  }

   /**
   * Get sortFields
   * @return sortFields
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SsaReportDefinitionServiceReportSortField> getSortFields() {
    return sortFields;
  }


  @JsonProperty(JSON_PROPERTY_SORT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSortFields(List<SsaReportDefinitionServiceReportSortField> sortFields) {
    this.sortFields = sortFields;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SsaReportDefinition ssaReportDefinition = (SsaReportDefinition) o;
    return Objects.equals(this.accountId, ssaReportDefinition.accountId) &&
        Objects.equals(this.completeTime, ssaReportDefinition.completeTime) &&
        Objects.equals(this.dateRange, ssaReportDefinition.dateRange) &&
        Objects.equals(this.fields, ssaReportDefinition.fields) &&
        Objects.equals(this.filters, ssaReportDefinition.filters) &&
        Objects.equals(this.reportCompressType, ssaReportDefinition.reportCompressType) &&
        Objects.equals(this.reportDateRangeType, ssaReportDefinition.reportDateRangeType) &&
        Objects.equals(this.reportDecimalPartDisplayType, ssaReportDefinition.reportDecimalPartDisplayType) &&
        Objects.equals(this.reportDownloadEncode, ssaReportDefinition.reportDownloadEncode) &&
        Objects.equals(this.reportDownloadFormat, ssaReportDefinition.reportDownloadFormat) &&
        Objects.equals(this.reportJobErrorDetail, ssaReportDefinition.reportJobErrorDetail) &&
        Objects.equals(this.reportJobId, ssaReportDefinition.reportJobId) &&
        Objects.equals(this.reportJobStatus, ssaReportDefinition.reportJobStatus) &&
        Objects.equals(this.reportLanguage, ssaReportDefinition.reportLanguage) &&
        Objects.equals(this.reportName, ssaReportDefinition.reportName) &&
        Objects.equals(this.reportSkipColumnHeader, ssaReportDefinition.reportSkipColumnHeader) &&
        Objects.equals(this.reportSkipReportSummary, ssaReportDefinition.reportSkipReportSummary) &&
        Objects.equals(this.reportType, ssaReportDefinition.reportType) &&
        Objects.equals(this.requestTime, ssaReportDefinition.requestTime) &&
        Objects.equals(this.sortFields, ssaReportDefinition.sortFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, completeTime, dateRange, fields, filters, reportCompressType, reportDateRangeType, reportDecimalPartDisplayType, reportDownloadEncode, reportDownloadFormat, reportJobErrorDetail, reportJobId, reportJobStatus, reportLanguage, reportName, reportSkipColumnHeader, reportSkipReportSummary, reportType, requestTime, sortFields);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SsaReportDefinition {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    completeTime: ").append(toIndentedString(completeTime)).append("\n");
    sb.append("    dateRange: ").append(toIndentedString(dateRange)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    reportCompressType: ").append(toIndentedString(reportCompressType)).append("\n");
    sb.append("    reportDateRangeType: ").append(toIndentedString(reportDateRangeType)).append("\n");
    sb.append("    reportDecimalPartDisplayType: ").append(toIndentedString(reportDecimalPartDisplayType)).append("\n");
    sb.append("    reportDownloadEncode: ").append(toIndentedString(reportDownloadEncode)).append("\n");
    sb.append("    reportDownloadFormat: ").append(toIndentedString(reportDownloadFormat)).append("\n");
    sb.append("    reportJobErrorDetail: ").append(toIndentedString(reportJobErrorDetail)).append("\n");
    sb.append("    reportJobId: ").append(toIndentedString(reportJobId)).append("\n");
    sb.append("    reportJobStatus: ").append(toIndentedString(reportJobStatus)).append("\n");
    sb.append("    reportLanguage: ").append(toIndentedString(reportLanguage)).append("\n");
    sb.append("    reportName: ").append(toIndentedString(reportName)).append("\n");
    sb.append("    reportSkipColumnHeader: ").append(toIndentedString(reportSkipColumnHeader)).append("\n");
    sb.append("    reportSkipReportSummary: ").append(toIndentedString(reportSkipReportSummary)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("    requestTime: ").append(toIndentedString(requestTime)).append("\n");
    sb.append("    sortFields: ").append(toIndentedString(sortFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

