/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v7/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v7.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceApprovalStatus;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceEncoding;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceEntityType;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceLang;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceOutput;
import jp.co.yahoo.adssearchapi.v7.model.CampaignExportServiceUserStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;CampaignExportServiceExportSetting オブジェクトは、エクスポートする条件を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;CampaignExportServiceExportSetting object describes the condition for exports.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">CampaignExportServiceExportSetting オブジェクトは、エクスポートする条件を表します。</div> <div lang=\"en\">CampaignExportServiceExportSetting object describes the condition for exports.</div> ")
@JsonPropertyOrder({
  CampaignExportServiceExportSetting.JSON_PROPERTY_ACCOUNT_ID,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_AD_APPROVAL_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_AD_USER_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_CRITERION_APPROVAL_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_CRITERION_IDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_CRITERION_USER_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_IDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_GROUP_USER_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_AD_IDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_CAMPAIGN_CRITERION_IDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_CAMPAIGN_IDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_CAMPAIGN_USER_STATUSES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_ENCODING,
  CampaignExportServiceExportSetting.JSON_PROPERTY_ENTITY_TYPES,
  CampaignExportServiceExportSetting.JSON_PROPERTY_EXPORT_FIELDS,
  CampaignExportServiceExportSetting.JSON_PROPERTY_JOB_NAME,
  CampaignExportServiceExportSetting.JSON_PROPERTY_LANG,
  CampaignExportServiceExportSetting.JSON_PROPERTY_OUTPUT
})
@JsonTypeName("CampaignExportServiceExportSetting")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CampaignExportServiceExportSetting {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  private Long accountId;

  public static final String JSON_PROPERTY_AD_GROUP_AD_APPROVAL_STATUSES = "adGroupAdApprovalStatuses";
  private List<CampaignExportServiceApprovalStatus> adGroupAdApprovalStatuses = null;

  public static final String JSON_PROPERTY_AD_GROUP_AD_USER_STATUSES = "adGroupAdUserStatuses";
  private List<CampaignExportServiceUserStatus> adGroupAdUserStatuses = null;

  public static final String JSON_PROPERTY_AD_GROUP_CRITERION_APPROVAL_STATUSES = "adGroupCriterionApprovalStatuses";
  private List<CampaignExportServiceApprovalStatus> adGroupCriterionApprovalStatuses = null;

  public static final String JSON_PROPERTY_AD_GROUP_CRITERION_IDS = "adGroupCriterionIds";
  private List<Long> adGroupCriterionIds = null;

  public static final String JSON_PROPERTY_AD_GROUP_CRITERION_USER_STATUSES = "adGroupCriterionUserStatuses";
  private List<CampaignExportServiceUserStatus> adGroupCriterionUserStatuses = null;

  public static final String JSON_PROPERTY_AD_GROUP_IDS = "adGroupIds";
  private List<Long> adGroupIds = null;

  public static final String JSON_PROPERTY_AD_GROUP_USER_STATUSES = "adGroupUserStatuses";
  private List<CampaignExportServiceUserStatus> adGroupUserStatuses = null;

  public static final String JSON_PROPERTY_AD_IDS = "adIds";
  private List<Long> adIds = null;

  public static final String JSON_PROPERTY_CAMPAIGN_CRITERION_IDS = "campaignCriterionIds";
  private List<Long> campaignCriterionIds = null;

  public static final String JSON_PROPERTY_CAMPAIGN_IDS = "campaignIds";
  private List<Long> campaignIds = null;

  public static final String JSON_PROPERTY_CAMPAIGN_USER_STATUSES = "campaignUserStatuses";
  private List<CampaignExportServiceUserStatus> campaignUserStatuses = null;

  public static final String JSON_PROPERTY_ENCODING = "encoding";
  private CampaignExportServiceEncoding encoding;

  public static final String JSON_PROPERTY_ENTITY_TYPES = "entityTypes";
  private List<CampaignExportServiceEntityType> entityTypes = null;

  public static final String JSON_PROPERTY_EXPORT_FIELDS = "exportFields";
  private List<String> exportFields = null;

  public static final String JSON_PROPERTY_JOB_NAME = "jobName";
  private String jobName;

  public static final String JSON_PROPERTY_LANG = "lang";
  private CampaignExportServiceLang lang;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  private CampaignExportServiceOutput output;

  public CampaignExportServiceExportSetting() { 
  }

  public CampaignExportServiceExportSetting accountId(Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウントIDです。&lt;br&gt;このフィールドは、必須です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account ID.&lt;br&gt;This field is required.&lt;/div&gt; 
   * @return accountId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "<div lang=\"ja\">アカウントIDです。<br>このフィールドは、必須です。</div> <div lang=\"en\">Account ID.<br>This field is required.</div> ")
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }


  public CampaignExportServiceExportSetting adGroupAdApprovalStatuses(List<CampaignExportServiceApprovalStatus> adGroupAdApprovalStatuses) {
    
    this.adGroupAdApprovalStatuses = adGroupAdApprovalStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupAdApprovalStatusesItem(CampaignExportServiceApprovalStatus adGroupAdApprovalStatusesItem) {
    if (this.adGroupAdApprovalStatuses == null) {
      this.adGroupAdApprovalStatuses = new ArrayList<>();
    }
    this.adGroupAdApprovalStatuses.add(adGroupAdApprovalStatusesItem);
    return this;
  }

   /**
   * Get adGroupAdApprovalStatuses
   * @return adGroupAdApprovalStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_AD_APPROVAL_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceApprovalStatus> getAdGroupAdApprovalStatuses() {
    return adGroupAdApprovalStatuses;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_AD_APPROVAL_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupAdApprovalStatuses(List<CampaignExportServiceApprovalStatus> adGroupAdApprovalStatuses) {
    this.adGroupAdApprovalStatuses = adGroupAdApprovalStatuses;
  }


  public CampaignExportServiceExportSetting adGroupAdUserStatuses(List<CampaignExportServiceUserStatus> adGroupAdUserStatuses) {
    
    this.adGroupAdUserStatuses = adGroupAdUserStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupAdUserStatusesItem(CampaignExportServiceUserStatus adGroupAdUserStatusesItem) {
    if (this.adGroupAdUserStatuses == null) {
      this.adGroupAdUserStatuses = new ArrayList<>();
    }
    this.adGroupAdUserStatuses.add(adGroupAdUserStatusesItem);
    return this;
  }

   /**
   * Get adGroupAdUserStatuses
   * @return adGroupAdUserStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_AD_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceUserStatus> getAdGroupAdUserStatuses() {
    return adGroupAdUserStatuses;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_AD_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupAdUserStatuses(List<CampaignExportServiceUserStatus> adGroupAdUserStatuses) {
    this.adGroupAdUserStatuses = adGroupAdUserStatuses;
  }


  public CampaignExportServiceExportSetting adGroupCriterionApprovalStatuses(List<CampaignExportServiceApprovalStatus> adGroupCriterionApprovalStatuses) {
    
    this.adGroupCriterionApprovalStatuses = adGroupCriterionApprovalStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupCriterionApprovalStatusesItem(CampaignExportServiceApprovalStatus adGroupCriterionApprovalStatusesItem) {
    if (this.adGroupCriterionApprovalStatuses == null) {
      this.adGroupCriterionApprovalStatuses = new ArrayList<>();
    }
    this.adGroupCriterionApprovalStatuses.add(adGroupCriterionApprovalStatusesItem);
    return this;
  }

   /**
   * Get adGroupCriterionApprovalStatuses
   * @return adGroupCriterionApprovalStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_APPROVAL_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceApprovalStatus> getAdGroupCriterionApprovalStatuses() {
    return adGroupCriterionApprovalStatuses;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_APPROVAL_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupCriterionApprovalStatuses(List<CampaignExportServiceApprovalStatus> adGroupCriterionApprovalStatuses) {
    this.adGroupCriterionApprovalStatuses = adGroupCriterionApprovalStatuses;
  }


  public CampaignExportServiceExportSetting adGroupCriterionIds(List<Long> adGroupCriterionIds) {
    
    this.adGroupCriterionIds = adGroupCriterionIds;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupCriterionIdsItem(Long adGroupCriterionIdsItem) {
    if (this.adGroupCriterionIds == null) {
      this.adGroupCriterionIds = new ArrayList<>();
    }
    this.adGroupCriterionIds.add(adGroupCriterionIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告グループクライテリアIDです。&lt;br&gt;このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Ad group criteria ID.&lt;br&gt;This field is optional.&lt;/div&gt; 
   * @return adGroupCriterionIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告グループクライテリアIDです。<br>このフィールドは、省略可能となります。</div> <div lang=\"en\">Ad group criteria ID.<br>This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getAdGroupCriterionIds() {
    return adGroupCriterionIds;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupCriterionIds(List<Long> adGroupCriterionIds) {
    this.adGroupCriterionIds = adGroupCriterionIds;
  }


  public CampaignExportServiceExportSetting adGroupCriterionUserStatuses(List<CampaignExportServiceUserStatus> adGroupCriterionUserStatuses) {
    
    this.adGroupCriterionUserStatuses = adGroupCriterionUserStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupCriterionUserStatusesItem(CampaignExportServiceUserStatus adGroupCriterionUserStatusesItem) {
    if (this.adGroupCriterionUserStatuses == null) {
      this.adGroupCriterionUserStatuses = new ArrayList<>();
    }
    this.adGroupCriterionUserStatuses.add(adGroupCriterionUserStatusesItem);
    return this;
  }

   /**
   * Get adGroupCriterionUserStatuses
   * @return adGroupCriterionUserStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceUserStatus> getAdGroupCriterionUserStatuses() {
    return adGroupCriterionUserStatuses;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_CRITERION_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupCriterionUserStatuses(List<CampaignExportServiceUserStatus> adGroupCriterionUserStatuses) {
    this.adGroupCriterionUserStatuses = adGroupCriterionUserStatuses;
  }


  public CampaignExportServiceExportSetting adGroupIds(List<Long> adGroupIds) {
    
    this.adGroupIds = adGroupIds;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupIdsItem(Long adGroupIdsItem) {
    if (this.adGroupIds == null) {
      this.adGroupIds = new ArrayList<>();
    }
    this.adGroupIds.add(adGroupIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ダウンロード対象の広告グループIDです。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Ad group ID of export objective.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return adGroupIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ダウンロード対象の広告グループIDです。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Ad group ID of export objective.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getAdGroupIds() {
    return adGroupIds;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupIds(List<Long> adGroupIds) {
    this.adGroupIds = adGroupIds;
  }


  public CampaignExportServiceExportSetting adGroupUserStatuses(List<CampaignExportServiceUserStatus> adGroupUserStatuses) {
    
    this.adGroupUserStatuses = adGroupUserStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addAdGroupUserStatusesItem(CampaignExportServiceUserStatus adGroupUserStatusesItem) {
    if (this.adGroupUserStatuses == null) {
      this.adGroupUserStatuses = new ArrayList<>();
    }
    this.adGroupUserStatuses.add(adGroupUserStatusesItem);
    return this;
  }

   /**
   * Get adGroupUserStatuses
   * @return adGroupUserStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_GROUP_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceUserStatus> getAdGroupUserStatuses() {
    return adGroupUserStatuses;
  }


  @JsonProperty(JSON_PROPERTY_AD_GROUP_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdGroupUserStatuses(List<CampaignExportServiceUserStatus> adGroupUserStatuses) {
    this.adGroupUserStatuses = adGroupUserStatuses;
  }


  public CampaignExportServiceExportSetting adIds(List<Long> adIds) {
    
    this.adIds = adIds;
    return this;
  }

  public CampaignExportServiceExportSetting addAdIdsItem(Long adIdsItem) {
    if (this.adIds == null) {
      this.adIds = new ArrayList<>();
    }
    this.adIds.add(adIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ダウンロード対象の広告IDです。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Ad ID of export objective.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return adIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ダウンロード対象の広告IDです。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Ad ID of export objective.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_AD_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getAdIds() {
    return adIds;
  }


  @JsonProperty(JSON_PROPERTY_AD_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdIds(List<Long> adIds) {
    this.adIds = adIds;
  }


  public CampaignExportServiceExportSetting campaignCriterionIds(List<Long> campaignCriterionIds) {
    
    this.campaignCriterionIds = campaignCriterionIds;
    return this;
  }

  public CampaignExportServiceExportSetting addCampaignCriterionIdsItem(Long campaignCriterionIdsItem) {
    if (this.campaignCriterionIds == null) {
      this.campaignCriterionIds = new ArrayList<>();
    }
    this.campaignCriterionIds.add(campaignCriterionIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;キャンペーンクライテリアIDです。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Campaign criteria ID.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return campaignCriterionIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">キャンペーンクライテリアIDです。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Campaign criteria ID.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_CRITERION_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getCampaignCriterionIds() {
    return campaignCriterionIds;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_CRITERION_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignCriterionIds(List<Long> campaignCriterionIds) {
    this.campaignCriterionIds = campaignCriterionIds;
  }


  public CampaignExportServiceExportSetting campaignIds(List<Long> campaignIds) {
    
    this.campaignIds = campaignIds;
    return this;
  }

  public CampaignExportServiceExportSetting addCampaignIdsItem(Long campaignIdsItem) {
    if (this.campaignIds == null) {
      this.campaignIds = new ArrayList<>();
    }
    this.campaignIds.add(campaignIdsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ダウンロード対象のキャンペーンIDです。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Campaign ID of export objective.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return campaignIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ダウンロード対象のキャンペーンIDです。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Campaign ID of export objective.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getCampaignIds() {
    return campaignIds;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignIds(List<Long> campaignIds) {
    this.campaignIds = campaignIds;
  }


  public CampaignExportServiceExportSetting campaignUserStatuses(List<CampaignExportServiceUserStatus> campaignUserStatuses) {
    
    this.campaignUserStatuses = campaignUserStatuses;
    return this;
  }

  public CampaignExportServiceExportSetting addCampaignUserStatusesItem(CampaignExportServiceUserStatus campaignUserStatusesItem) {
    if (this.campaignUserStatuses == null) {
      this.campaignUserStatuses = new ArrayList<>();
    }
    this.campaignUserStatuses.add(campaignUserStatusesItem);
    return this;
  }

   /**
   * Get campaignUserStatuses
   * @return campaignUserStatuses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAMPAIGN_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceUserStatus> getCampaignUserStatuses() {
    return campaignUserStatuses;
  }


  @JsonProperty(JSON_PROPERTY_CAMPAIGN_USER_STATUSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCampaignUserStatuses(List<CampaignExportServiceUserStatus> campaignUserStatuses) {
    this.campaignUserStatuses = campaignUserStatuses;
  }


  public CampaignExportServiceExportSetting encoding(CampaignExportServiceEncoding encoding) {
    
    this.encoding = encoding;
    return this;
  }

   /**
   * Get encoding
   * @return encoding
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENCODING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CampaignExportServiceEncoding getEncoding() {
    return encoding;
  }


  @JsonProperty(JSON_PROPERTY_ENCODING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEncoding(CampaignExportServiceEncoding encoding) {
    this.encoding = encoding;
  }


  public CampaignExportServiceExportSetting entityTypes(List<CampaignExportServiceEntityType> entityTypes) {
    
    this.entityTypes = entityTypes;
    return this;
  }

  public CampaignExportServiceExportSetting addEntityTypesItem(CampaignExportServiceEntityType entityTypesItem) {
    if (this.entityTypes == null) {
      this.entityTypes = new ArrayList<>();
    }
    this.entityTypes.add(entityTypesItem);
    return this;
  }

   /**
   * Get entityTypes
   * @return entityTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENTITY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CampaignExportServiceEntityType> getEntityTypes() {
    return entityTypes;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityTypes(List<CampaignExportServiceEntityType> entityTypes) {
    this.entityTypes = entityTypes;
  }


  public CampaignExportServiceExportSetting exportFields(List<String> exportFields) {
    
    this.exportFields = exportFields;
    return this;
  }

  public CampaignExportServiceExportSetting addExportFieldsItem(String exportFieldsItem) {
    if (this.exportFields == null) {
      this.exportFields = new ArrayList<>();
    }
    this.exportFields.add(exportFieldsItem);
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;エクスポートするフィールドを指定します。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Select which field to export.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return exportFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">エクスポートするフィールドを指定します。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Select which field to export.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_EXPORT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExportFields() {
    return exportFields;
  }


  @JsonProperty(JSON_PROPERTY_EXPORT_FIELDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExportFields(List<String> exportFields) {
    this.exportFields = exportFields;
  }


  public CampaignExportServiceExportSetting jobName(String jobName) {
    
    this.jobName = jobName;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ダウンロードするジョブの名称です。&lt;br&gt; このフィールドは、省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Job information for export.&lt;br&gt; This field is optional.&lt;/div&gt; 
   * @return jobName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ダウンロードするジョブの名称です。<br> このフィールドは、省略可能となります。</div> <div lang=\"en\">Job information for export.<br> This field is optional.</div> ")
  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobName() {
    return jobName;
  }


  @JsonProperty(JSON_PROPERTY_JOB_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobName(String jobName) {
    this.jobName = jobName;
  }


  public CampaignExportServiceExportSetting lang(CampaignExportServiceLang lang) {
    
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CampaignExportServiceLang getLang() {
    return lang;
  }


  @JsonProperty(JSON_PROPERTY_LANG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLang(CampaignExportServiceLang lang) {
    this.lang = lang;
  }


  public CampaignExportServiceExportSetting output(CampaignExportServiceOutput output) {
    
    this.output = output;
    return this;
  }

   /**
   * Get output
   * @return output
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CampaignExportServiceOutput getOutput() {
    return output;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOutput(CampaignExportServiceOutput output) {
    this.output = output;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignExportServiceExportSetting campaignExportServiceExportSetting = (CampaignExportServiceExportSetting) o;
    return Objects.equals(this.accountId, campaignExportServiceExportSetting.accountId) &&
        Objects.equals(this.adGroupAdApprovalStatuses, campaignExportServiceExportSetting.adGroupAdApprovalStatuses) &&
        Objects.equals(this.adGroupAdUserStatuses, campaignExportServiceExportSetting.adGroupAdUserStatuses) &&
        Objects.equals(this.adGroupCriterionApprovalStatuses, campaignExportServiceExportSetting.adGroupCriterionApprovalStatuses) &&
        Objects.equals(this.adGroupCriterionIds, campaignExportServiceExportSetting.adGroupCriterionIds) &&
        Objects.equals(this.adGroupCriterionUserStatuses, campaignExportServiceExportSetting.adGroupCriterionUserStatuses) &&
        Objects.equals(this.adGroupIds, campaignExportServiceExportSetting.adGroupIds) &&
        Objects.equals(this.adGroupUserStatuses, campaignExportServiceExportSetting.adGroupUserStatuses) &&
        Objects.equals(this.adIds, campaignExportServiceExportSetting.adIds) &&
        Objects.equals(this.campaignCriterionIds, campaignExportServiceExportSetting.campaignCriterionIds) &&
        Objects.equals(this.campaignIds, campaignExportServiceExportSetting.campaignIds) &&
        Objects.equals(this.campaignUserStatuses, campaignExportServiceExportSetting.campaignUserStatuses) &&
        Objects.equals(this.encoding, campaignExportServiceExportSetting.encoding) &&
        Objects.equals(this.entityTypes, campaignExportServiceExportSetting.entityTypes) &&
        Objects.equals(this.exportFields, campaignExportServiceExportSetting.exportFields) &&
        Objects.equals(this.jobName, campaignExportServiceExportSetting.jobName) &&
        Objects.equals(this.lang, campaignExportServiceExportSetting.lang) &&
        Objects.equals(this.output, campaignExportServiceExportSetting.output);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, adGroupAdApprovalStatuses, adGroupAdUserStatuses, adGroupCriterionApprovalStatuses, adGroupCriterionIds, adGroupCriterionUserStatuses, adGroupIds, adGroupUserStatuses, adIds, campaignCriterionIds, campaignIds, campaignUserStatuses, encoding, entityTypes, exportFields, jobName, lang, output);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignExportServiceExportSetting {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    adGroupAdApprovalStatuses: ").append(toIndentedString(adGroupAdApprovalStatuses)).append("\n");
    sb.append("    adGroupAdUserStatuses: ").append(toIndentedString(adGroupAdUserStatuses)).append("\n");
    sb.append("    adGroupCriterionApprovalStatuses: ").append(toIndentedString(adGroupCriterionApprovalStatuses)).append("\n");
    sb.append("    adGroupCriterionIds: ").append(toIndentedString(adGroupCriterionIds)).append("\n");
    sb.append("    adGroupCriterionUserStatuses: ").append(toIndentedString(adGroupCriterionUserStatuses)).append("\n");
    sb.append("    adGroupIds: ").append(toIndentedString(adGroupIds)).append("\n");
    sb.append("    adGroupUserStatuses: ").append(toIndentedString(adGroupUserStatuses)).append("\n");
    sb.append("    adIds: ").append(toIndentedString(adIds)).append("\n");
    sb.append("    campaignCriterionIds: ").append(toIndentedString(campaignCriterionIds)).append("\n");
    sb.append("    campaignIds: ").append(toIndentedString(campaignIds)).append("\n");
    sb.append("    campaignUserStatuses: ").append(toIndentedString(campaignUserStatuses)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    entityTypes: ").append(toIndentedString(entityTypes)).append("\n");
    sb.append("    exportFields: ").append(toIndentedString(exportFields)).append("\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

