/*
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adssearchapi.v6.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceAdType;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceAdditionalAdvancedMobileUrls;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceAdditionalAdvancedUrls;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceAppAd;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceCustomParameters;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceDevicePreference;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceDynamicSearchLinkedAd;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceExtendedTextAd;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceResponsiveSearchAd;
import jp.co.yahoo.adssearchapi.v6.model.AdGroupAdServiceTextAd2;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AdGroupAdServiceAdオブジェクトは、広告に関する情報を表します。&lt;br&gt; ADD時、このフィールドは必須となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AdGroupAdServiceAd object describes ad information.&lt;br&gt; This field is required in ADD operation.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">AdGroupAdServiceAdオブジェクトは、広告に関する情報を表します。<br> ADD時、このフィールドは必須となります。</div> <div lang=\"en\">AdGroupAdServiceAd object describes ad information.<br> This field is required in ADD operation.</div> ")
@JsonPropertyOrder({
  AdGroupAdServiceAd.JSON_PROPERTY_AD_TYPE,
  AdGroupAdServiceAd.JSON_PROPERTY_ADDITIONAL_ADVANCED_MOBILE_URLS,
  AdGroupAdServiceAd.JSON_PROPERTY_ADDITIONAL_ADVANCED_URLS,
  AdGroupAdServiceAd.JSON_PROPERTY_ADVANCED_MOBILE_URL,
  AdGroupAdServiceAd.JSON_PROPERTY_ADVANCED_URL,
  AdGroupAdServiceAd.JSON_PROPERTY_APP_AD,
  AdGroupAdServiceAd.JSON_PROPERTY_CUSTOM_PARAMETERS,
  AdGroupAdServiceAd.JSON_PROPERTY_DESCRIPTION1,
  AdGroupAdServiceAd.JSON_PROPERTY_DEVICE_PREFERENCE,
  AdGroupAdServiceAd.JSON_PROPERTY_DISPLAY_URL,
  AdGroupAdServiceAd.JSON_PROPERTY_EXTENDED_TEXT_AD,
  AdGroupAdServiceAd.JSON_PROPERTY_RESPONSIVE_SEARCH_AD,
  AdGroupAdServiceAd.JSON_PROPERTY_HEADLINE1,
  AdGroupAdServiceAd.JSON_PROPERTY_TEXT_AD2,
  AdGroupAdServiceAd.JSON_PROPERTY_DYNAMIC_SEARCH_LINKED_AD,
  AdGroupAdServiceAd.JSON_PROPERTY_TRACKING_URL,
  AdGroupAdServiceAd.JSON_PROPERTY_URL
})
@JsonTypeName("AdGroupAdServiceAd")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AdGroupAdServiceAd {
  public static final String JSON_PROPERTY_AD_TYPE = "adType";
  private AdGroupAdServiceAdType adType;

  public static final String JSON_PROPERTY_ADDITIONAL_ADVANCED_MOBILE_URLS = "additionalAdvancedMobileUrls";
  private List<AdGroupAdServiceAdditionalAdvancedMobileUrls> additionalAdvancedMobileUrls = null;

  public static final String JSON_PROPERTY_ADDITIONAL_ADVANCED_URLS = "additionalAdvancedUrls";
  private List<AdGroupAdServiceAdditionalAdvancedUrls> additionalAdvancedUrls = null;

  public static final String JSON_PROPERTY_ADVANCED_MOBILE_URL = "advancedMobileUrl";
  private String advancedMobileUrl;

  public static final String JSON_PROPERTY_ADVANCED_URL = "advancedUrl";
  private String advancedUrl;

  public static final String JSON_PROPERTY_APP_AD = "appAd";
  private AdGroupAdServiceAppAd appAd;

  public static final String JSON_PROPERTY_CUSTOM_PARAMETERS = "customParameters";
  private AdGroupAdServiceCustomParameters customParameters;

  public static final String JSON_PROPERTY_DESCRIPTION1 = "description1";
  private String description1;

  public static final String JSON_PROPERTY_DEVICE_PREFERENCE = "devicePreference";
  private AdGroupAdServiceDevicePreference devicePreference;

  public static final String JSON_PROPERTY_DISPLAY_URL = "displayUrl";
  private String displayUrl;

  public static final String JSON_PROPERTY_EXTENDED_TEXT_AD = "extendedTextAd";
  private AdGroupAdServiceExtendedTextAd extendedTextAd;

  public static final String JSON_PROPERTY_RESPONSIVE_SEARCH_AD = "responsiveSearchAd";
  private AdGroupAdServiceResponsiveSearchAd responsiveSearchAd;

  public static final String JSON_PROPERTY_HEADLINE1 = "headline1";
  private String headline1;

  public static final String JSON_PROPERTY_TEXT_AD2 = "textAd2";
  private AdGroupAdServiceTextAd2 textAd2;

  public static final String JSON_PROPERTY_DYNAMIC_SEARCH_LINKED_AD = "dynamicSearchLinkedAd";
  private AdGroupAdServiceDynamicSearchLinkedAd dynamicSearchLinkedAd;

  public static final String JSON_PROPERTY_TRACKING_URL = "trackingUrl";
  private String trackingUrl;

  public static final String JSON_PROPERTY_URL = "url";
  private String url;

  public AdGroupAdServiceAd() { 
  }

  public AdGroupAdServiceAd adType(AdGroupAdServiceAdType adType) {
    
    this.adType = adType;
    return this;
  }

   /**
   * Get adType
   * @return adType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceAdType getAdType() {
    return adType;
  }


  @JsonProperty(JSON_PROPERTY_AD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdType(AdGroupAdServiceAdType adType) {
    this.adType = adType;
  }


  public AdGroupAdServiceAd additionalAdvancedMobileUrls(List<AdGroupAdServiceAdditionalAdvancedMobileUrls> additionalAdvancedMobileUrls) {
    
    this.additionalAdvancedMobileUrls = additionalAdvancedMobileUrls;
    return this;
  }

  public AdGroupAdServiceAd addAdditionalAdvancedMobileUrlsItem(AdGroupAdServiceAdditionalAdvancedMobileUrls additionalAdvancedMobileUrlsItem) {
    if (this.additionalAdvancedMobileUrls == null) {
      this.additionalAdvancedMobileUrls = new ArrayList<>();
    }
    this.additionalAdvancedMobileUrls.add(additionalAdvancedMobileUrlsItem);
    return this;
  }

   /**
   * Get additionalAdvancedMobileUrls
   * @return additionalAdvancedMobileUrls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADVANCED_MOBILE_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdGroupAdServiceAdditionalAdvancedMobileUrls> getAdditionalAdvancedMobileUrls() {
    return additionalAdvancedMobileUrls;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADVANCED_MOBILE_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalAdvancedMobileUrls(List<AdGroupAdServiceAdditionalAdvancedMobileUrls> additionalAdvancedMobileUrls) {
    this.additionalAdvancedMobileUrls = additionalAdvancedMobileUrls;
  }


  public AdGroupAdServiceAd additionalAdvancedUrls(List<AdGroupAdServiceAdditionalAdvancedUrls> additionalAdvancedUrls) {
    
    this.additionalAdvancedUrls = additionalAdvancedUrls;
    return this;
  }

  public AdGroupAdServiceAd addAdditionalAdvancedUrlsItem(AdGroupAdServiceAdditionalAdvancedUrls additionalAdvancedUrlsItem) {
    if (this.additionalAdvancedUrls == null) {
      this.additionalAdvancedUrls = new ArrayList<>();
    }
    this.additionalAdvancedUrls.add(additionalAdvancedUrlsItem);
    return this;
  }

   /**
   * Get additionalAdvancedUrls
   * @return additionalAdvancedUrls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADVANCED_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdGroupAdServiceAdditionalAdvancedUrls> getAdditionalAdvancedUrls() {
    return additionalAdvancedUrls;
  }


  @JsonProperty(JSON_PROPERTY_ADDITIONAL_ADVANCED_URLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdditionalAdvancedUrls(List<AdGroupAdServiceAdditionalAdvancedUrls> additionalAdvancedUrls) {
    this.additionalAdvancedUrls = additionalAdvancedUrls;
  }


  public AdGroupAdServiceAd advancedMobileUrl(String advancedMobileUrl) {
    
    this.advancedMobileUrl = advancedMobileUrl;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;スマートフォン向けURLです。&lt;br&gt; ADD時、このフィールドは省略可能となります。※adTypeがDYNAMIC_SEARCH_LINKED_ADの場合は無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Smartphone final URL.&lt;br&gt; This field is optional in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD, this field will be ignored.&lt;/div&gt; 
   * @return advancedMobileUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">スマートフォン向けURLです。<br> ADD時、このフィールドは省略可能となります。※adTypeがDYNAMIC_SEARCH_LINKED_ADの場合は無視されます。</div> <div lang=\"en\">Smartphone final URL.<br> This field is optional in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD, this field will be ignored.</div> ")
  @JsonProperty(JSON_PROPERTY_ADVANCED_MOBILE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdvancedMobileUrl() {
    return advancedMobileUrl;
  }


  @JsonProperty(JSON_PROPERTY_ADVANCED_MOBILE_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvancedMobileUrl(String advancedMobileUrl) {
    this.advancedMobileUrl = advancedMobileUrl;
  }


  public AdGroupAdServiceAd advancedUrl(String advancedUrl) {
    
    this.advancedUrl = advancedUrl;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;最終リンク先URLです。&lt;br&gt; ADD時、このフィールドは必須となります。※adTypeがDYNAMIC_SEARCH_LINKED_ADの場合は無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Final URL.&lt;br&gt; This field is required in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD, this field will be ignored.&lt;/div&gt; 
   * @return advancedUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">最終リンク先URLです。<br> ADD時、このフィールドは必須となります。※adTypeがDYNAMIC_SEARCH_LINKED_ADの場合は無視されます。</div> <div lang=\"en\">Final URL.<br> This field is required in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD, this field will be ignored.</div> ")
  @JsonProperty(JSON_PROPERTY_ADVANCED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdvancedUrl() {
    return advancedUrl;
  }


  @JsonProperty(JSON_PROPERTY_ADVANCED_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvancedUrl(String advancedUrl) {
    this.advancedUrl = advancedUrl;
  }


  public AdGroupAdServiceAd appAd(AdGroupAdServiceAppAd appAd) {
    
    this.appAd = appAd;
    return this;
  }

   /**
   * Get appAd
   * @return appAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_APP_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceAppAd getAppAd() {
    return appAd;
  }


  @JsonProperty(JSON_PROPERTY_APP_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppAd(AdGroupAdServiceAppAd appAd) {
    this.appAd = appAd;
  }


  public AdGroupAdServiceAd customParameters(AdGroupAdServiceCustomParameters customParameters) {
    
    this.customParameters = customParameters;
    return this;
  }

   /**
   * Get customParameters
   * @return customParameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CUSTOM_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceCustomParameters getCustomParameters() {
    return customParameters;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOM_PARAMETERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomParameters(AdGroupAdServiceCustomParameters customParameters) {
    this.customParameters = customParameters;
  }


  public AdGroupAdServiceAd description1(String description1) {
    
    this.description1 = description1;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;説明文です。&lt;br&gt; ADD時、このフィールドは必須となります。※adTypeがRESPONSIVE_SEARCH_ADの場合は無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Description of ad.&lt;br&gt; This field is required in ADD operation. *If adType is RESPONSIVE_SEARCH_AD, this field will be ignored.&lt;/div&gt; 
   * @return description1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">説明文です。<br> ADD時、このフィールドは必須となります。※adTypeがRESPONSIVE_SEARCH_ADの場合は無視されます。</div> <div lang=\"en\">Description of ad.<br> This field is required in ADD operation. *If adType is RESPONSIVE_SEARCH_AD, this field will be ignored.</div> ")
  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription1() {
    return description1;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription1(String description1) {
    this.description1 = description1;
  }


  public AdGroupAdServiceAd devicePreference(AdGroupAdServiceDevicePreference devicePreference) {
    
    this.devicePreference = devicePreference;
    return this;
  }

   /**
   * Get devicePreference
   * @return devicePreference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEVICE_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceDevicePreference getDevicePreference() {
    return devicePreference;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_PREFERENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevicePreference(AdGroupAdServiceDevicePreference devicePreference) {
    this.devicePreference = devicePreference;
  }


  public AdGroupAdServiceAd displayUrl(String displayUrl) {
    
    this.displayUrl = displayUrl;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;表示URLです。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Display URL.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input.&lt;/div&gt; 
   * @return displayUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">表示URLです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Display URL.<br> Although this field will be returned in the response, it will be ignored on input.</div> ")
  @JsonProperty(JSON_PROPERTY_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayUrl() {
    return displayUrl;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayUrl(String displayUrl) {
    this.displayUrl = displayUrl;
  }


  public AdGroupAdServiceAd extendedTextAd(AdGroupAdServiceExtendedTextAd extendedTextAd) {
    
    this.extendedTextAd = extendedTextAd;
    return this;
  }

   /**
   * Get extendedTextAd
   * @return extendedTextAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXTENDED_TEXT_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceExtendedTextAd getExtendedTextAd() {
    return extendedTextAd;
  }


  @JsonProperty(JSON_PROPERTY_EXTENDED_TEXT_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExtendedTextAd(AdGroupAdServiceExtendedTextAd extendedTextAd) {
    this.extendedTextAd = extendedTextAd;
  }


  public AdGroupAdServiceAd responsiveSearchAd(AdGroupAdServiceResponsiveSearchAd responsiveSearchAd) {
    
    this.responsiveSearchAd = responsiveSearchAd;
    return this;
  }

   /**
   * Get responsiveSearchAd
   * @return responsiveSearchAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_RESPONSIVE_SEARCH_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceResponsiveSearchAd getResponsiveSearchAd() {
    return responsiveSearchAd;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSIVE_SEARCH_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponsiveSearchAd(AdGroupAdServiceResponsiveSearchAd responsiveSearchAd) {
    this.responsiveSearchAd = responsiveSearchAd;
  }


  public AdGroupAdServiceAd headline1(String headline1) {
    
    this.headline1 = headline1;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;タイトル文です。&lt;br&gt; ADD時、このフィールドは必須となります。※adTypeがDYNAMIC_SEARCH_LINKED_AD、またはRESPONSIVE_SEARCH_ADの場合は無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Title of ad.&lt;br&gt; This field is required in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD or RESPONSIVE_SEARCH_AD, this field will be ignored.&lt;/div&gt; 
   * @return headline1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">タイトル文です。<br> ADD時、このフィールドは必須となります。※adTypeがDYNAMIC_SEARCH_LINKED_AD、またはRESPONSIVE_SEARCH_ADの場合は無視されます。</div> <div lang=\"en\">Title of ad.<br> This field is required in ADD operation. *If adType is DYNAMIC_SEARCH_LINKED_AD or RESPONSIVE_SEARCH_AD, this field will be ignored.</div> ")
  @JsonProperty(JSON_PROPERTY_HEADLINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHeadline1() {
    return headline1;
  }


  @JsonProperty(JSON_PROPERTY_HEADLINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeadline1(String headline1) {
    this.headline1 = headline1;
  }


  public AdGroupAdServiceAd textAd2(AdGroupAdServiceTextAd2 textAd2) {
    
    this.textAd2 = textAd2;
    return this;
  }

   /**
   * Get textAd2
   * @return textAd2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TEXT_AD2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceTextAd2 getTextAd2() {
    return textAd2;
  }


  @JsonProperty(JSON_PROPERTY_TEXT_AD2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTextAd2(AdGroupAdServiceTextAd2 textAd2) {
    this.textAd2 = textAd2;
  }


  public AdGroupAdServiceAd dynamicSearchLinkedAd(AdGroupAdServiceDynamicSearchLinkedAd dynamicSearchLinkedAd) {
    
    this.dynamicSearchLinkedAd = dynamicSearchLinkedAd;
    return this;
  }

   /**
   * Get dynamicSearchLinkedAd
   * @return dynamicSearchLinkedAd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DYNAMIC_SEARCH_LINKED_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AdGroupAdServiceDynamicSearchLinkedAd getDynamicSearchLinkedAd() {
    return dynamicSearchLinkedAd;
  }


  @JsonProperty(JSON_PROPERTY_DYNAMIC_SEARCH_LINKED_AD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDynamicSearchLinkedAd(AdGroupAdServiceDynamicSearchLinkedAd dynamicSearchLinkedAd) {
    this.dynamicSearchLinkedAd = dynamicSearchLinkedAd;
  }


  public AdGroupAdServiceAd trackingUrl(String trackingUrl) {
    
    this.trackingUrl = trackingUrl;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;トラッキングURLです。&lt;br&gt; ADD時、このフィールドは省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Tracking URL.&lt;br&gt; This field is optional in ADD operation.&lt;/div&gt; 
   * @return trackingUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">トラッキングURLです。<br> ADD時、このフィールドは省略可能となります。</div> <div lang=\"en\">Tracking URL.<br> This field is optional in ADD operation.</div> ")
  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTrackingUrl() {
    return trackingUrl;
  }


  @JsonProperty(JSON_PROPERTY_TRACKING_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingUrl(String trackingUrl) {
    this.trackingUrl = trackingUrl;
  }


  public AdGroupAdServiceAd url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;移行前のリンク先URLです。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Destination URL before upgrading. &lt;br&gt; Although this field will be returned in the response, it will be ignored on input.&lt;/div&gt; 
   * @return url
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">移行前のリンク先URLです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Destination URL before upgrading. <br> Although this field will be returned in the response, it will be ignored on input.</div> ")
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdGroupAdServiceAd adGroupAdServiceAd = (AdGroupAdServiceAd) o;
    return Objects.equals(this.adType, adGroupAdServiceAd.adType) &&
        Objects.equals(this.additionalAdvancedMobileUrls, adGroupAdServiceAd.additionalAdvancedMobileUrls) &&
        Objects.equals(this.additionalAdvancedUrls, adGroupAdServiceAd.additionalAdvancedUrls) &&
        Objects.equals(this.advancedMobileUrl, adGroupAdServiceAd.advancedMobileUrl) &&
        Objects.equals(this.advancedUrl, adGroupAdServiceAd.advancedUrl) &&
        Objects.equals(this.appAd, adGroupAdServiceAd.appAd) &&
        Objects.equals(this.customParameters, adGroupAdServiceAd.customParameters) &&
        Objects.equals(this.description1, adGroupAdServiceAd.description1) &&
        Objects.equals(this.devicePreference, adGroupAdServiceAd.devicePreference) &&
        Objects.equals(this.displayUrl, adGroupAdServiceAd.displayUrl) &&
        Objects.equals(this.extendedTextAd, adGroupAdServiceAd.extendedTextAd) &&
        Objects.equals(this.responsiveSearchAd, adGroupAdServiceAd.responsiveSearchAd) &&
        Objects.equals(this.headline1, adGroupAdServiceAd.headline1) &&
        Objects.equals(this.textAd2, adGroupAdServiceAd.textAd2) &&
        Objects.equals(this.dynamicSearchLinkedAd, adGroupAdServiceAd.dynamicSearchLinkedAd) &&
        Objects.equals(this.trackingUrl, adGroupAdServiceAd.trackingUrl) &&
        Objects.equals(this.url, adGroupAdServiceAd.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adType, additionalAdvancedMobileUrls, additionalAdvancedUrls, advancedMobileUrl, advancedUrl, appAd, customParameters, description1, devicePreference, displayUrl, extendedTextAd, responsiveSearchAd, headline1, textAd2, dynamicSearchLinkedAd, trackingUrl, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdGroupAdServiceAd {\n");
    sb.append("    adType: ").append(toIndentedString(adType)).append("\n");
    sb.append("    additionalAdvancedMobileUrls: ").append(toIndentedString(additionalAdvancedMobileUrls)).append("\n");
    sb.append("    additionalAdvancedUrls: ").append(toIndentedString(additionalAdvancedUrls)).append("\n");
    sb.append("    advancedMobileUrl: ").append(toIndentedString(advancedMobileUrl)).append("\n");
    sb.append("    advancedUrl: ").append(toIndentedString(advancedUrl)).append("\n");
    sb.append("    appAd: ").append(toIndentedString(appAd)).append("\n");
    sb.append("    customParameters: ").append(toIndentedString(customParameters)).append("\n");
    sb.append("    description1: ").append(toIndentedString(description1)).append("\n");
    sb.append("    devicePreference: ").append(toIndentedString(devicePreference)).append("\n");
    sb.append("    displayUrl: ").append(toIndentedString(displayUrl)).append("\n");
    sb.append("    extendedTextAd: ").append(toIndentedString(extendedTextAd)).append("\n");
    sb.append("    responsiveSearchAd: ").append(toIndentedString(responsiveSearchAd)).append("\n");
    sb.append("    headline1: ").append(toIndentedString(headline1)).append("\n");
    sb.append("    textAd2: ").append(toIndentedString(textAd2)).append("\n");
    sb.append("    dynamicSearchLinkedAd: ").append(toIndentedString(dynamicSearchLinkedAd)).append("\n");
    sb.append("    trackingUrl: ").append(toIndentedString(trackingUrl)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

